//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ugur_Form_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UgurFormsModel : DbContext
    {
        public UgurFormsModel()
            : base("name=UgurFormsModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bilgiler> Bilgiler { get; set; }
        public virtual DbSet<Durum> Durum { get; set; }
        public virtual DbSet<Nitelik> Nitelik { get; set; }
        public virtual DbSet<Olay> Olay { get; set; }
        //public object Bilgiler { get; internal set; }
    }
}
